export * from './about/about.component'
export * from './brand/brand.component'
export * from './forgot-password/forgot-password.component'
export * from './home/home.component'
export * from './login/login.component'
export * from './register/register.component'